//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Educacion
    {
        public int EducacionId { get; set; }
        public int UsuarioId { get; set; }
        public string Titulo { get; set; }
        public string EstablecimientoEducativo { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public System.DateTime FechaHasta { get; set; }
        public string Estado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
