//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienciaLaboral
    {
        public int ExperienciaLaboralId { get; set; }
        public int UsuarioId { get; set; }
        public string Puesto { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string ReferenciaNombre { get; set; }
        public Nullable<int> ReferenciaTelefono { get; set; }
        public Nullable<bool> Actualidad { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
