USE [master]
GO
/****** Object:  Database [CV]    Script Date: 30/7/2020 17:46:48 ******/
CREATE DATABASE [CV]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CV', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLMARTIN\MSSQL\DATA\CV.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CV_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLMARTIN\MSSQL\DATA\CV_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CV] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CV].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CV] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CV] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CV] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CV] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CV] SET ARITHABORT OFF 
GO
ALTER DATABASE [CV] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CV] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CV] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CV] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CV] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CV] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CV] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CV] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CV] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CV] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CV] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CV] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CV] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CV] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CV] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CV] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CV] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CV] SET RECOVERY FULL 
GO
ALTER DATABASE [CV] SET  MULTI_USER 
GO
ALTER DATABASE [CV] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CV] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CV] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CV] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CV] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'CV', N'ON'
GO
ALTER DATABASE [CV] SET QUERY_STORE = OFF
GO
USE [CV]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [CV]
GO
/****** Object:  Table [dbo].[Conocimiento]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Conocimiento](
	[ConocimientoId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Descripcion] [varchar](200) NOT NULL,
	[Nivel] [varchar](20) NOT NULL,
 CONSTRAINT [PK_Conocimiento] PRIMARY KEY CLUSTERED 
(
	[ConocimientoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DatosPersonales]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DatosPersonales](
	[DatospersonalesId] [int] IDENTITY(1,1) NOT NULL,
	[Nombres] [varchar](100) NOT NULL,
	[Apellido] [varchar](100) NOT NULL,
	[FechaNacimiento] [date] NOT NULL,
	[Nacionalidad] [varchar](50) NOT NULL,
	[LugarNacimiento] [varchar](200) NOT NULL,
	[Domicilio] [varchar](200) NOT NULL,
	[NroDomicilio] [int] NULL,
	[CodigoPostal] [varchar](10) NULL,
	[Email] [varchar](100) NULL,
	[Telefono] [int] NULL,
	[UsuarioId] [int] NOT NULL,
	[Profesion] [varchar](100) NULL,
	[Git] [varchar](100) NULL,
	[Linkedin] [varchar](100) NULL,
 CONSTRAINT [PK_DatosPersonales] PRIMARY KEY CLUSTERED 
(
	[DatospersonalesId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Educacion]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Educacion](
	[EducacionId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Titulo] [varchar](100) NOT NULL,
	[EstablecimientoEducativo] [varchar](200) NOT NULL,
	[FechaDesde] [date] NOT NULL,
	[FechaHasta] [date] NOT NULL,
	[Estado] [varchar](10) NOT NULL,
	[Comentario] [varchar](200) NULL,
	[link] [varchar](200) NULL,
 CONSTRAINT [PK_Educacion] PRIMARY KEY CLUSTERED 
(
	[EducacionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ExperienciaLaboral]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ExperienciaLaboral](
	[ExperienciaLaboralId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Puesto] [varchar](100) NOT NULL,
	[Descripcion] [varchar](200) NOT NULL,
	[FechaDesde] [date] NOT NULL,
	[FechaHasta] [date] NULL,
	[ReferenciaNombre] [varchar](50) NULL,
	[ReferenciaTelefono] [int] NULL,
	[Actualidad] [bit] NULL,
 CONSTRAINT [PK_ExperienciaLaboral] PRIMARY KEY CLUSTERED 
(
	[ExperienciaLaboralId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Idioma]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Idioma](
	[IdiomaId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[NivelEscrito] [varchar](30) NOT NULL,
	[NivelOral] [varchar](30) NOT NULL,
	[Descripcion] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Idioma] PRIMARY KEY CLUSTERED 
(
	[IdiomaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Imagen]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Imagen](
	[ImagenId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Nombre] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Imagen] PRIMARY KEY CLUSTERED 
(
	[ImagenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Objetivo]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Objetivo](
	[ObjetivoId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioId] [int] NOT NULL,
	[Descripcion] [varchar](200) NOT NULL,
 CONSTRAINT [PK_Objetivo] PRIMARY KEY CLUSTERED 
(
	[ObjetivoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 30/7/2020 17:46:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[UsuarioId] [int] IDENTITY(1,1) NOT NULL,
	[UsuarioNombre] [varchar](30) NOT NULL,
	[UsuarioPassword] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Usuario] PRIMARY KEY CLUSTERED 
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Conocimiento]  WITH CHECK ADD  CONSTRAINT [FK_Conocimiento_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[Conocimiento] CHECK CONSTRAINT [FK_Conocimiento_Usuario]
GO
ALTER TABLE [dbo].[DatosPersonales]  WITH CHECK ADD  CONSTRAINT [FK_DatosPersonales_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[DatosPersonales] CHECK CONSTRAINT [FK_DatosPersonales_Usuario]
GO
ALTER TABLE [dbo].[Educacion]  WITH CHECK ADD  CONSTRAINT [FK_Educacion_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[Educacion] CHECK CONSTRAINT [FK_Educacion_Usuario]
GO
ALTER TABLE [dbo].[ExperienciaLaboral]  WITH CHECK ADD  CONSTRAINT [FK_ExperienciaLaboral_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[ExperienciaLaboral] CHECK CONSTRAINT [FK_ExperienciaLaboral_Usuario]
GO
ALTER TABLE [dbo].[Idioma]  WITH CHECK ADD  CONSTRAINT [FK_Idioma_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[Idioma] CHECK CONSTRAINT [FK_Idioma_Usuario]
GO
ALTER TABLE [dbo].[Imagen]  WITH CHECK ADD  CONSTRAINT [FK_Imagen_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[Imagen] CHECK CONSTRAINT [FK_Imagen_Usuario]
GO
ALTER TABLE [dbo].[Objetivo]  WITH CHECK ADD  CONSTRAINT [FK_Objetivo_Usuario] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuario] ([UsuarioId])
GO
ALTER TABLE [dbo].[Objetivo] CHECK CONSTRAINT [FK_Objetivo_Usuario]
GO
USE [master]
GO
ALTER DATABASE [CV] SET  READ_WRITE 
GO
